global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/aa6222b3-a344-4a8b-a43f-c8deb06442a1'
          send_resolved: false